spring.application.name=notification-service
server.port=8082

spring.kafka.bootstrap-servers=kafka:9092

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=notification-service
eureka.instance.instance-id=notification-service:8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kostavasilyev85@gmail.com
spring.mail.password=zuzkykdsgxwcgkut

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.smtp.from=kostavasilyev85@gmail.com
